/*
 * This file is generated by jOOQ.
 */
package br.com.evandropires.debitauthorizer.jooq;


import br.com.evandropires.debitauthorizer.jooq.tables.Account;
import br.com.evandropires.debitauthorizer.jooq.tables.Balance;
import br.com.evandropires.debitauthorizer.jooq.tables.Debitcard;
import br.com.evandropires.debitauthorizer.jooq.tables.Provisionaldebit;
import br.com.evandropires.debitauthorizer.jooq.tables.Transaction;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACCOUNT_PK = Indexes0.ACCOUNT_PK;
    public static final Index BALANCE_PK = Indexes0.BALANCE_PK;
    public static final Index DEBITCARD_PKEY = Indexes0.DEBITCARD_PKEY;
    public static final Index PROVISIONALDEBIT_PKEY = Indexes0.PROVISIONALDEBIT_PKEY;
    public static final Index TRANSACTION_PKEY = Indexes0.TRANSACTION_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ACCOUNT_PK = Internal.createIndex("account_pk", Account.ACCOUNT, new OrderField[] { Account.ACCOUNT.AGENCY, Account.ACCOUNT.ACCOUNTNUMBER }, true);
        public static Index BALANCE_PK = Internal.createIndex("balance_pk", Balance.BALANCE, new OrderField[] { Balance.BALANCE.AGENCY, Balance.BALANCE.ACCOUNTNUMBER }, true);
        public static Index DEBITCARD_PKEY = Internal.createIndex("debitcard_pkey", Debitcard.DEBITCARD, new OrderField[] { Debitcard.DEBITCARD.CARDNUMBER }, true);
        public static Index PROVISIONALDEBIT_PKEY = Internal.createIndex("provisionaldebit_pkey", Provisionaldebit.PROVISIONALDEBIT, new OrderField[] { Provisionaldebit.PROVISIONALDEBIT.ID }, true);
        public static Index TRANSACTION_PKEY = Internal.createIndex("transaction_pkey", Transaction.TRANSACTION, new OrderField[] { Transaction.TRANSACTION.ID }, true);
    }
}
