/*
 * This file is generated by jOOQ.
 */
package br.com.evandropires.debitauthorizer.jooq;


import br.com.evandropires.debitauthorizer.jooq.tables.Account;
import br.com.evandropires.debitauthorizer.jooq.tables.Balance;
import br.com.evandropires.debitauthorizer.jooq.tables.Debitcard;
import br.com.evandropires.debitauthorizer.jooq.tables.Provisionaldebit;
import br.com.evandropires.debitauthorizer.jooq.tables.Transaction;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1803233194;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.account</code>.
     */
    public final Account ACCOUNT = br.com.evandropires.debitauthorizer.jooq.tables.Account.ACCOUNT;

    /**
     * The table <code>public.balance</code>.
     */
    public final Balance BALANCE = br.com.evandropires.debitauthorizer.jooq.tables.Balance.BALANCE;

    /**
     * The table <code>public.debitcard</code>.
     */
    public final Debitcard DEBITCARD = br.com.evandropires.debitauthorizer.jooq.tables.Debitcard.DEBITCARD;

    /**
     * The table <code>public.provisionaldebit</code>.
     */
    public final Provisionaldebit PROVISIONALDEBIT = br.com.evandropires.debitauthorizer.jooq.tables.Provisionaldebit.PROVISIONALDEBIT;

    /**
     * The table <code>public.transaction</code>.
     */
    public final Transaction TRANSACTION = br.com.evandropires.debitauthorizer.jooq.tables.Transaction.TRANSACTION;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.PROVISIONALDEBIT_ID_SEQ,
            Sequences.TRANSACTION_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Account.ACCOUNT,
            Balance.BALANCE,
            Debitcard.DEBITCARD,
            Provisionaldebit.PROVISIONALDEBIT,
            Transaction.TRANSACTION);
    }
}
