/*
 * This file is generated by jOOQ.
 */
package br.com.evandropires.debitauthorizer.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.provisionaldebit_id_seq</code>
     */
    public static final Sequence<Long> PROVISIONALDEBIT_ID_SEQ = new SequenceImpl<Long>("provisionaldebit_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.transaction_id_seq</code>
     */
    public static final Sequence<Long> TRANSACTION_ID_SEQ = new SequenceImpl<Long>("transaction_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
