/*
 * This file is generated by jOOQ.
 */
package br.com.evandropires.debitauthorizer.jooq.tables.records;


import br.com.evandropires.debitauthorizer.jooq.tables.Debitcard;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DebitcardRecord extends UpdatableRecordImpl<DebitcardRecord> implements Record4<BigDecimal, Integer, Integer, String> {

    private static final long serialVersionUID = -949391957;

    /**
     * Setter for <code>public.debitcard.cardnumber</code>.
     */
    public void setCardnumber(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.debitcard.cardnumber</code>.
     */
    public BigDecimal getCardnumber() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>public.debitcard.agency</code>.
     */
    public void setAgency(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.debitcard.agency</code>.
     */
    public Integer getAgency() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.debitcard.account</code>.
     */
    public void setAccount(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.debitcard.account</code>.
     */
    public Integer getAccount() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.debitcard.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.debitcard.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<BigDecimal> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<BigDecimal, Integer, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<BigDecimal, Integer, Integer, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field1() {
        return Debitcard.DEBITCARD.CARDNUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Debitcard.DEBITCARD.AGENCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Debitcard.DEBITCARD.ACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Debitcard.DEBITCARD.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component1() {
        return getCardnumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getAgency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value1() {
        return getCardnumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getAgency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DebitcardRecord value1(BigDecimal value) {
        setCardnumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DebitcardRecord value2(Integer value) {
        setAgency(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DebitcardRecord value3(Integer value) {
        setAccount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DebitcardRecord value4(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DebitcardRecord values(BigDecimal value1, Integer value2, Integer value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DebitcardRecord
     */
    public DebitcardRecord() {
        super(Debitcard.DEBITCARD);
    }

    /**
     * Create a detached, initialised DebitcardRecord
     */
    public DebitcardRecord(BigDecimal cardnumber, Integer agency, Integer account, String status) {
        super(Debitcard.DEBITCARD);

        set(0, cardnumber);
        set(1, agency);
        set(2, account);
        set(3, status);
    }
}
