/*
 * This file is generated by jOOQ.
 */
package br.com.evandropires.debitauthorizer.jooq.tables.records;


import br.com.evandropires.debitauthorizer.jooq.tables.Provisionaldebit;

import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProvisionaldebitRecord extends UpdatableRecordImpl<ProvisionaldebitRecord> implements Record6<Integer, Integer, Integer, BigDecimal, Date, String> {

    private static final long serialVersionUID = -511786120;

    /**
     * Setter for <code>public.provisionaldebit.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.provisionaldebit.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.provisionaldebit.agency</code>.
     */
    public void setAgency(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.provisionaldebit.agency</code>.
     */
    public Integer getAgency() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.provisionaldebit.accountnumber</code>.
     */
    public void setAccountnumber(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.provisionaldebit.accountnumber</code>.
     */
    public Integer getAccountnumber() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.provisionaldebit.debitvalue</code>.
     */
    public void setDebitvalue(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.provisionaldebit.debitvalue</code>.
     */
    public BigDecimal getDebitvalue() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.provisionaldebit.debitdate</code>.
     */
    public void setDebitdate(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.provisionaldebit.debitdate</code>.
     */
    public Date getDebitdate() {
        return (Date) get(4);
    }

    /**
     * Setter for <code>public.provisionaldebit.status</code>.
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.provisionaldebit.status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, BigDecimal, Date, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, BigDecimal, Date, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Provisionaldebit.PROVISIONALDEBIT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Provisionaldebit.PROVISIONALDEBIT.AGENCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Provisionaldebit.PROVISIONALDEBIT.ACCOUNTNUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return Provisionaldebit.PROVISIONALDEBIT.DEBITVALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return Provisionaldebit.PROVISIONALDEBIT.DEBITDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Provisionaldebit.PROVISIONALDEBIT.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getAgency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getAccountnumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getDebitvalue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component5() {
        return getDebitdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getAgency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getAccountnumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getDebitvalue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getDebitdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvisionaldebitRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvisionaldebitRecord value2(Integer value) {
        setAgency(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvisionaldebitRecord value3(Integer value) {
        setAccountnumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvisionaldebitRecord value4(BigDecimal value) {
        setDebitvalue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvisionaldebitRecord value5(Date value) {
        setDebitdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvisionaldebitRecord value6(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvisionaldebitRecord values(Integer value1, Integer value2, Integer value3, BigDecimal value4, Date value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProvisionaldebitRecord
     */
    public ProvisionaldebitRecord() {
        super(Provisionaldebit.PROVISIONALDEBIT);
    }

    /**
     * Create a detached, initialised ProvisionaldebitRecord
     */
    public ProvisionaldebitRecord(Integer id, Integer agency, Integer accountnumber, BigDecimal debitvalue, Date debitdate, String status) {
        super(Provisionaldebit.PROVISIONALDEBIT);

        set(0, id);
        set(1, agency);
        set(2, accountnumber);
        set(3, debitvalue);
        set(4, debitdate);
        set(5, status);
    }
}
