/*
 * This file is generated by jOOQ.
 */
package br.com.evandropires.debitauthorizer.jooq.routines;


import br.com.evandropires.debitauthorizer.jooq.Public;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ComposeSessionReplicationRole extends AbstractRoutine<String> {

    private static final long serialVersionUID = 311523821;

    /**
     * The parameter <code>public.compose_session_replication_role.RETURN_VALUE</code>.
     */
    public static final Parameter<String> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>public.compose_session_replication_role.role</code>.
     */
    public static final Parameter<String> ROLE = createParameter("role", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public ComposeSessionReplicationRole() {
        super("compose_session_replication_role", Public.PUBLIC, org.jooq.impl.SQLDataType.CLOB);

        setReturnParameter(RETURN_VALUE);
        addInParameter(ROLE);
    }

    /**
     * Set the <code>role</code> parameter IN value to the routine
     */
    public void setRole(String value) {
        setValue(ROLE, value);
    }

    /**
     * Set the <code>role</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setRole(Field<String> field) {
        setField(ROLE, field);
    }
}
