/*
 * This file is generated by jOOQ.
 */
package br.com.evandropires.debitauthorizer.jooq.routines;


import br.com.evandropires.debitauthorizer.jooq.Public;

import javax.annotation.Generated;

import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UpgradePostgis_23x extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -2052770868;

    /**
     * Create a new routine call instance
     */
    public UpgradePostgis_23x() {
        super("upgrade_postgis_23x", Public.PUBLIC);
    }
}
