/*
 * This file is generated by jOOQ.
 */
package br.com.evandropires.debitauthorizer.jooq.tables;


import br.com.evandropires.debitauthorizer.jooq.Indexes;
import br.com.evandropires.debitauthorizer.jooq.Keys;
import br.com.evandropires.debitauthorizer.jooq.Public;
import br.com.evandropires.debitauthorizer.jooq.tables.records.ProvisionaldebitRecord;

import java.math.BigDecimal;
import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Provisionaldebit extends TableImpl<ProvisionaldebitRecord> {

    private static final long serialVersionUID = 545778199;

    /**
     * The reference instance of <code>public.provisionaldebit</code>
     */
    public static final Provisionaldebit PROVISIONALDEBIT = new Provisionaldebit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProvisionaldebitRecord> getRecordType() {
        return ProvisionaldebitRecord.class;
    }

    /**
     * The column <code>public.provisionaldebit.id</code>.
     */
    public final TableField<ProvisionaldebitRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('provisionaldebit_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.provisionaldebit.agency</code>.
     */
    public final TableField<ProvisionaldebitRecord, Integer> AGENCY = createField("agency", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.provisionaldebit.accountnumber</code>.
     */
    public final TableField<ProvisionaldebitRecord, Integer> ACCOUNTNUMBER = createField("accountnumber", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.provisionaldebit.debitvalue</code>.
     */
    public final TableField<ProvisionaldebitRecord, BigDecimal> DEBITVALUE = createField("debitvalue", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.provisionaldebit.debitdate</code>.
     */
    public final TableField<ProvisionaldebitRecord, Date> DEBITDATE = createField("debitdate", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>public.provisionaldebit.status</code>.
     */
    public final TableField<ProvisionaldebitRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.provisionaldebit</code> table reference
     */
    public Provisionaldebit() {
        this(DSL.name("provisionaldebit"), null);
    }

    /**
     * Create an aliased <code>public.provisionaldebit</code> table reference
     */
    public Provisionaldebit(String alias) {
        this(DSL.name(alias), PROVISIONALDEBIT);
    }

    /**
     * Create an aliased <code>public.provisionaldebit</code> table reference
     */
    public Provisionaldebit(Name alias) {
        this(alias, PROVISIONALDEBIT);
    }

    private Provisionaldebit(Name alias, Table<ProvisionaldebitRecord> aliased) {
        this(alias, aliased, null);
    }

    private Provisionaldebit(Name alias, Table<ProvisionaldebitRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Provisionaldebit(Table<O> child, ForeignKey<O, ProvisionaldebitRecord> key) {
        super(child, key, PROVISIONALDEBIT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PROVISIONALDEBIT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ProvisionaldebitRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PROVISIONALDEBIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProvisionaldebitRecord> getPrimaryKey() {
        return Keys.PROVISIONALDEBIT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProvisionaldebitRecord>> getKeys() {
        return Arrays.<UniqueKey<ProvisionaldebitRecord>>asList(Keys.PROVISIONALDEBIT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Provisionaldebit as(String alias) {
        return new Provisionaldebit(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Provisionaldebit as(Name alias) {
        return new Provisionaldebit(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Provisionaldebit rename(String name) {
        return new Provisionaldebit(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Provisionaldebit rename(Name name) {
        return new Provisionaldebit(name, null);
    }
}
